<a href="https://colab.research.google.com/github/gaeun1018/Class_ML/blob/main/%EC%8B%AC%EC%B8%B5%ED%95%99%EC%8A%B5_percettron_xor.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
epsilon = 0.00000001
def step_func(t):
  if t>epsilon:return 1
  else: return 0

In [ ]:
import numpy as np

X = np.array([
    [0, 0, 1],
    [0, 1, 1],
    [1, 0, 1],
    [1, 1, 1]
])

y = np.array([0, 1, 1, 0])

In [ ]:
W = np.zeros(len(X[0]))

In [ ]:
print(y)
print(X[0])
print(len(X[0]))
print(W)

[0 1 1 0]
[0 0 1]
3
[0. 0. 0.]


In [ ]:
def perceptron_fit(X, Y, epochs=6):
  global W
  eta = 0.2

  for t in  range(epochs):
    for i in range(len(X)):
      predict = step_func(np.dot(X[i],W))
      error = Y[i] - predict
      W += eta * error * X[i]
      print("현재처리입력=",X[i], "정답=",Y[i], "오차=",error,"출력=",predict, "변경된가중치=", W)
      print("================================")


In [ ]:
 perceptron_fit(X, y, 10)

현재처리입력= [0 0 1] 정답= 0 오차= 0 출력= 0 변경된가중치= [0. 0. 0.]
현재처리입력= [0 1 1] 정답= 1 오차= 1 출력= 0 변경된가중치= [0.  0.2 0.2]
현재처리입력= [1 0 1] 정답= 1 오차= 0 출력= 1 변경된가중치= [0.  0.2 0.2]
현재처리입력= [1 1 1] 정답= 0 오차= -1 출력= 1 변경된가중치= [-0.2  0.   0. ]
현재처리입력= [0 0 1] 정답= 0 오차= 0 출력= 0 변경된가중치= [-0.2  0.   0. ]
현재처리입력= [0 1 1] 정답= 1 오차= 1 출력= 0 변경된가중치= [-0.2  0.2  0.2]
현재처리입력= [1 0 1] 정답= 1 오차= 1 출력= 0 변경된가중치= [0.  0.2 0.4]
현재처리입력= [1 1 1] 정답= 0 오차= -1 출력= 1 변경된가중치= [-0.2  0.   0.2]
현재처리입력= [0 0 1] 정답= 0 오차= -1 출력= 1 변경된가중치= [-0.2  0.   0. ]
현재처리입력= [0 1 1] 정답= 1 오차= 1 출력= 0 변경된가중치= [-0.2  0.2  0.2]
현재처리입력= [1 0 1] 정답= 1 오차= 1 출력= 0 변경된가중치= [0.  0.2 0.4]
현재처리입력= [1 1 1] 정답= 0 오차= -1 출력= 1 변경된가중치= [-0.2  0.   0.2]
현재처리입력= [0 0 1] 정답= 0 오차= -1 출력= 1 변경된가중치= [-0.2  0.   0. ]
현재처리입력= [0 1 1] 정답= 1 오차= 1 출력= 0 변경된가중치= [-0.2  0.2  0.2]
현재처리입력= [1 0 1] 정답= 1 오차= 1 출력= 0 변경된가중치= [0.  0.2 0.4]
현재처리입력= [1 1 1] 정답= 0 오차= -1 출력= 1 변경된가중치= [-0.2  0.   0.2]
현재처리입력= [0 0 1] 정답= 0 오차= -1 출력= 1 변경된가중치= [-0.2  0.   0. ]
현재처리입력= [0 

In [ ]:
def perceptron_predict(X, Y):
  global W
  for x in X:
    print(x[0], x[1], "->", step_func(np.dot(x, W)))

In [ ]:
perceptron_predict(X, y)

0 0 -> 1
0 1 -> 1
1 0 -> 0
1 1 -> 0
